name: Create issues across prods and levels

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    strategy:
      matrix:
        prod: [prod1, prod2]
        level: [dev, stage, rel]
    uses: chanelcolgate/started-forex-trading-python-algorithm/.github/workflows/create-issue-via-gh.yml@main
    secrets: inherit
    with:
      title: "${{ matrix.prod }} issue"
      body: "Update for ${{ matrix.level }}"

  request-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-number }}