name: Create demo via gh

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    uses: chanelcolgate/started-forex-trading-python-algorithm/.github/workflows/create-issue-via-gh.yml@main
    secrets: inherit
    with:
      title: "Test issue"
      body: "Test body"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-number }}