name: Create demo issue

on:
  workflow_dispatch:

jobs:
  msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simple demo for resuable workflow"

  info:
    uses: chanelcolgate/started-forex-trading-python-algorithm/.github/workflows/create-repo-issue.yml@main
    secrets:
      token: ${{ secrets.WORKFLOW_PAT }}
    with:
      title: "Test issue"
      body: "Test body"